name: Flag Service CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - TC_fase03

permissions:
  contents: read
  id-token: write

jobs:
  
  ci:
    name: Flag Service CI

    uses: astronomaelaine/CI-reusable-source-py/blob/main/.github/ci-reusable.yml

    permissions:
      contents: read
      id-token: write

    with:
      aws-region: ${{ vars.AWS_REGION }}
      aws-role-arn: ${{ vars.AWS_ROLE_ARN }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      image-name: "flag-service"
      app-version: ${{ vars.APP_VERSION }}